name: WWW-Scraper-ISBN-TWYlib_Driver
version: 0.01
abstract: Search driver for TWYlib's online catalog.
author: Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Test::More: 0
  WWW::Scraper::ISBN: 0.25
  WWW::Scraper::ISBN::Driver: 0.18
  Template::Extract: 0.40
  WWW::Mechanize: 1.16
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
